# Generated by Django 5.1.7 on 2025-03-24 16:06

import django.core.validators
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(editable=False, help_text="Unique four-digit ID (auto-generated, e.g., '1000')", max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'ID must be a four-digit number.')])),
                ('name', models.CharField(help_text="Department name (e.g., 'Computer Science')", max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s&]+$', "Name must contain only letters, spaces, or '&'.")])),
                ('faculty', models.CharField(choices=[('I&C', 'IC'), ('E&T', 'ET'), ('I&R', 'IR'), ('LS', 'LS'), ('LAMS', 'LAMS'), ('MS', 'MS'), ('SC', 'SC'), ('CCSD', 'CCSD')], help_text="Faculty affiliation (e.g., 'I&C')", max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft deletion flag')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, help_text='User who created this department', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_departments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, help_text='User who last updated this department', null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['faculty'], name='academics_d_faculty_3673e6_idx'), models.Index(fields=['created_at'], name='academics_d_created_227bed_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name', 'faculty'), name='unique_active_name_faculty')],
            },
        ),
    ]
