# Generated by Django 5.1.7 on 2025-03-24 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.CharField(choices=[('I&C', 'Information Computing'), ('E&T', 'Engineering Technology'), ('I&R', 'Interdisciplinary Research'), ('LS', 'Life Sciences'), ('LAMS', 'Liberal Arts Media'), ('MS', 'Management Studies'), ('SC', 'Sciences'), ('CCSD', 'Ccsd')], help_text='Faculty affiliation', max_length=4),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(editable=False, help_text='Unique four-digit ID (auto-generated)', max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'ID must be a four-digit number')]),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text="Department name (e.g., 'Computer Science')", max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s&]+$', "Name must contain only letters, spaces, or '&'")]),
        ),
    ]
